# Generated by Django 2.0.6 on 2018-07-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='userimg',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='userimage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
