# Generated by Django 2.0.6 on 2018-07-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KB', '0002_auto_20180704_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
